
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sqlauditor
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      completions: 1  #at least one success
      backoffLimit: 3 #retries
      template:
        spec:
          containers:
          - name: sqlauditor
            image: lenisha/sqlauditor
            volumeMounts:
            - name: config
              mountPath: /app/appsettings.json
              subPath: appsettings.Development.json
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          ## kubectl create configmap sqlauditor-settings --from-file appsettings.Development.json
          volumes:
          - name: config 
            configMap:
              name: sqlauditor-settings   